### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by ListenQ** [GalensGan/UZonMail#33]
- 安装包下载链接打不开
- 文档链接地址打不开

**Comment by GalensGan** [comment]
> - 安装包下载链接打不开
> - 文档链接地址打不开

修复了，服务器断电了关机了。
使用说明见：https://uzonmail.pages.dev

**Comment by ListenQ** [comment]
> > * 安装包下载链接打不开
> > * 文档链接地址打不开
> 
> 修复了，服务器断电了关机了。 使用说明见：https://uzonmail.pages.dev

可以了，多谢~
