### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ListenQ** [GalensGan/UZonMail#34]
执行 ./build-desktop.ps1 

```
$ ./build-desktop.ps1
./build-desktop.ps1: line 1: $'\357\273\277.': command not found
```

**Comment by GalensGan** [comment]
应该是你 powershell 的版本太低，我用的是 powershell 7.3.4，你可以参考下。

**Comment by ListenQ** [comment]
> 应该是你 powershell 的版本太低，我用的是 powershell 7.3.4，你可以参考下。

```
./build-desktop.ps1 : 无法加载文件 F:\UZonMail-master\UZonMail-master\scripts\build-desktop.ps1，因为在此系统上禁止运行
脚本。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ ./build-desktop.ps1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by GalensGan** [comment]
您需要开发吗？如果仅是使用的话，请直接下载既有的编译版本，这个编译需要很多环境，编译可能会遇到一些问题。
这个错误需要你手动允许本地脚本运行：`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`
这些错误可以通过 gpt 得到解决

**Comment by ListenQ** [comment]
> 您需要开发吗？如果仅是使用的话，请直接下载既有的编译版本，这个编译需要很多环境，编译可能会遇到一些问题。 这个错误需要你手动允许本地脚本运行：`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` 这些错误可以通过 gpt 得到解决

好的，感谢~ 主要是批量发送时，总是发送失败

**Comment by GalensGan** [comment]
发送失败后，从【发件历史】中，右键，进入到明细。鼠标放到"失败"上面，会显示失败的原因。
编译的版本实测没问题，很多用户都在用。

**Comment by ListenQ** [comment]
> 发送失败后，从【发件历史】中，右键，进入到明细。鼠标放到"失败"上面，会显示失败的原因。 编译的版本实测没问题，很多用户都在用。

好的，看到原因了，在体验中发现有一个问题
现象：第一次新建发件是正常发送，后面在点到 新建发件界面，此时看到主题，模版，数据，发件人和收件人等都有数据了，然后重新上传一下数据的表格，点立即发送会出现全部失败，在历史发件查看明细是看到 主题和发件箱是空白的

**Comment by GalensGan** [comment]
失败的原因是什么呢？

**Comment by ListenQ** [comment]
> 失败的原因是什么呢？

原因是猜测的，应该是新建发件界面输入框有自动记住上一次填的内容，但是点击发送后拿不到值，拿到的值是空的，才导致上面失败的界面，主题是空白，发件箱是空白

**Comment by GalensGan** [comment]
我的意思是，你可以将鼠标放到状态上的【失败】上面，会显示失败的原因，我怀疑是发件箱有问题，导致任务退出了

**Comment by ListenQ** [comment]
> 我的意思是，你可以将鼠标放到状态上的【失败】上面，会显示失败的原因，我怀疑是发件箱有问题，导致任务退出了

![image](https://github.com/user-attachments/assets/40dfe4f4-9fef-4df6-a043-10a985f22901)
![image](https://github.com/user-attachments/assets/0061bf46-bd3c-4267-b819-55cb02816c15)

**Comment by GalensGan** [comment]
发件任务结束是由你发件箱错误导致的，smtp 服务连接断开了。
这个不是软件bug导致的，主题和发件箱空白没问题，因为你的发件箱出了问题，这两封邮件没有发送。

**Comment by ListenQ** [comment]
> 我的意思是，你可以将鼠标放到状态上的【失败】上面，会显示失败的原因，我怀疑是发件箱有问题，导致任务退出了



> 发件任务结束是由你发件箱错误导致的，smtp 服务连接断开了。 这个不是软件bug导致的，主题和发件箱空白没问题，因为你的发件箱出了问题，这两封邮件没有发送。

确实如你所说问题，重发后是成功了，主题和发件箱有数据了
smtp服务链接超时导致？同样的发件箱有时正常有时失败
